# readme_example-grammar

#######################################################################
#
#  EBNF-Directives
#
#######################################################################

@ whitespace  = vertical        # implicit whitespace, includes any number of line feeds
@ literalws   = right           # literals have implicit whitespace on the right hand side
@ comment     = /#.*/           # comments range from a '#'-character to the end of the line
@ ignorecase  = False           # literals and regular expressions are case-sensitive
@ drop        = whitespace, strings


#######################################################################
#
#:  Structure and Components
#
#######################################################################

key_store   = ~ { entry }
entry       = key "=" value
key         = /\w+/~                  # Scannerless parsing: Use regular expressions
value       = /\"[^"\n]*\"/~          # expressions wherever you like

