@whitespace = horizontal
@disposable = EOF, LF, SAME_INDENT
@drop       = strings, whitespace, EOF, LF, SAME_INDENT
tree     = { INDENT node DEDENT } /\s*/ EOF
node     = tag_name [content]

content  = string | children
children = &(LF HAS_DEEPER_INDENT)
           LF INDENT § node { LF SAME_INDENT § node }
           !(LF HAS_DEEPER_INDENT) DEDENT
tag_name = /\w+/~
string   = '"' § /(?:\\"|[^"\n])*/ '"' ~

INDENT            = / */
SAME_INDENT       = :INDENT § !/ /
HAS_DEEPER_INDENT = :INDENT / +/
DEDENT            = &:?INDENT
LF       = /\n/
EOF      = !/./
