# miniXML-grammar

#######################################################################
#
#  EBNF-Directives
#
#######################################################################

@ whitespace  = /\s*/
@ disposable  = EOF
@ drop        = EOF, whitespace, strings

document = ~ element ~ §EOF
element  = STag content ETag
STag     = '<' TagName §'>'
@ETag_skip = :?TagName /[^>]*/
ETag     = '</' §::TagName '>'
TagName  = /\w+/
content  = [CharData] { (element | COMMENT__) [CharData] }

CharData = /(?:(?!\]\]>)[^<&])+/
EOF      =  !/./        # no more characters ahead, end of file reached
