# miniXML-grammar

#######################################################################
#
#  EBNF-Directives
#
#######################################################################

@ whitespace  = /\s*/
@ disposable  = EOF
@ drop        = EOF, whitespace, strings

document = ~ element ~ §EOF
element  = STag §content ETag
# @Stag_skip = (/[^<>]/)
STag     = '<' TagName §'>'
@ETag_skip = ((/\s*(?=>)/ | :?TagName) /[^<>]*/), /$/
# @ETag_resume = (`</` (/\s*>/ | :?TagName) /[^<>]*/ [`>`])
ETag     = '</' §::TagName '>'
TagName  = /\w+/
content  = [CharData] { (element | COMMENT__) [CharData] }

CharData = /(?:(?!\]\]>)[^<&])+/
EOF      =  !/./        # no more characters ahead, end of file reached
