# EBNF-Syntax von MLW-Einträgen (Versuch!!!)

@literalws = none     # no implicit whitespace around literals!


Lemma      = [Wortart] [Markierung] Eintrag
Wortart    = (ABKUERZUNG | BUCHSTABENFOLGE) LEERZEICHEN
Markierung = "*"

Eintrag    = Wort ["," Flexion] "." [Hinweis] LEERRAUM Bedeutung
Wort       = BUCHSTABENFOLGE
Flexion    = ALLES_BIS_PUNKT
Hinweis    = LEERRAUM
             (BEDEUTUNGSABSCHNITT !BEDEUTUNGSTRENNER !BEDEUTUNGSENDE)
Bedeutung  = TEXTBLOCK { LEERRAUM TEXTBLOCK }


TEXTBLOCK           = < !LEERRAUM (BUCHSTABENFOLGE | ZEICHEN) >
BEDEUTUNGSABSCHNITT = < !LEERRAUM !BEDEUTUNGSTRENNER !BEDEUTUNGSENDE
                        (BUCHSTABENFOLGE | ZEICHEN) >
ALLES_BIS_PUNKT     = /[^.]+/

NUMMER              = /[0-9]+/
BUCHSTABENFOLGE     = /\w+/
ABKUERZUNG          = /\w+\./
LEERZEICHEN         = /\s/
LEERRAUM            = /   /
BEDEUTUNGSTRENNER   = / - /
BEDEUTUNGSENDE      = /: /
ZEICHEN             = /./
