@braces_filter = counterpart_filter
document       = { text | codeblock }
codeblock      = braces { text | opening_braces | (!:braces closing_braces) } ::braces
braces         = opening_braces
opening_braces = /\{+/
closing_braces = /\}+/
text           = /[^{}]+/
