# ini-grammar

#######################################################################
#
#  EBNF-Directives
#
#######################################################################

# Regular expression for implicit whitespace or one of: horizontal, linefeed, vertical
# Implicit whitespace is denoted by the tilde-character: ~
@ whitespace  = vertical

# Implicit whitespace adjacent to literals: left, right, both, none
# E.g. if @literalws = right then ")" means the same as `)`~
@ literalws   = right

# Regular expression for comments, e.g. /#.*(?:\n|$)/
# Use: /(?:\/\/.*)|(?:\/\*(?:.|\n)*?\*\/)/ for C++-style comments: /* ... */ or // to EOL
@ comment     = /#.*/

# Case-sensitivity: True, False
@ ignorecase  = False

# Tree-simplification while parsing:  none, flatten, merge_anonymous_treetops, merge
@ reduction   = flatten         # anonymous nodes are being reduced where possible

# Tags that may be replaced with their content while parsing
@ disposable  = EOF, TEXTLINE

# Tags that will be dropped with all their content while parsing
# Here, EOF and insignificant whitespace (tilde) will be dropped
@ drop        = EOF, whitespace, strings, backticked


#######################################################################
#
# Fehlerbehandlung
#
#######################################################################

@heading_resume = /\n\s*(?=\w|\[)/
@entry_resume = /\n\s*(?=\w|\[)/

#######################################################################
#
#:  Structure and Components
#
#######################################################################

ini_file   = ~ { section } EOF
section    = heading { entry }
heading    = "[" § identifier "]"
entry      = identifier § ":" value
identifier = /\w+/~
value      = `"` § TEXTLINE '"'

#######################################################################
#
#:  Regular Expressions
#
#######################################################################

TEXTLINE = /[^"\n]*/
EOF      =  !/./        # no more characters ahead, end of file reached
