# BibTeX-Grammar

@ testing     = True
@ whitespace  = /\s*/
@ ignorecase  = True
@ comment     = /%.*(?:\n|$)/

bibliography = { preamble | comment | entry }

preamble      = "@Preamble{" /"/ pre_code /"/~ §"}"
pre_code      = { /[^"%]+/ | /%.*\n/ }

comment       = "@Comment{" text §"}"

entry         = /@/ type "{" key { "," field §"=" content } §"}"
type          = /\w+/
key           = /[^ \t\n,%]+/~
field         = /\w+/~
content       = "{" text "}" | plain_content

plain_content = { /[^,%]+/ | /(?=%)/~ }
text          = { /(?:\\\{|\\\}|[^}%])+/~ | /\{/ text /\}/ | /(?=%)/~ }
