/* Generated by the Nim Compiler v2.0.2 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI654311698 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI184549387 = {size: 0,kind: 34,base: null,node: null,finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI973078532 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI973078531 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI654311678 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI654311487 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554438 = {size: 0,kind: 34,base: null,node: null,finalizer: null};
var NTI654311429 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI654311427 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555835 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555173 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555181 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555180 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555178 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555178 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555178.node = NNI33555178;
NTI33555180.base = NTI33555177;
NTI33555181.base = NTI33555177;
var NNI33555177 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555180, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555181, name: "up", sons: null}]};
NTI33555177.node = NNI33555177;
var NNI33555173 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555173.node = NNI33555173;
NTI33555177.base = NTI33555173;
NTI33555178.base = NTI33555177;
NTI134217741.base = NTI33555178;
NTI134217743.base = NTI134217741;
var NNI33555835 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555835.node = NNI33555835;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555178;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555178;
NTI654311429.base = NTI33554449;
var NNI654311427 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "buf", len: 0, typ: NTI654311429, name: "buf", sons: null}, 
{kind: 1, offset: "start", len: 0, typ: NTI33554438, name: "start", sons: null}, 
{kind: 1, offset: "stop", len: 0, typ: NTI33554438, name: "stop", sons: null}]};
NTI654311427.node = NNI654311427;
var NNI654311487 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI33554438, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554438, name: "b", sons: null}]};
NTI654311487.node = NNI654311487;
var NNI973078532 = {kind: 2, len: 15, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "flags", len: 0, typ: NTI33554450, name: "flags", sons: null}, 
{kind: 1, offset: "dotAll", len: 0, typ: NTI33554466, name: "dotAll", sons: null}, 
{kind: 1, offset: "global", len: 0, typ: NTI33554466, name: "global", sons: null}, 
{kind: 1, offset: "ignoreCase", len: 0, typ: NTI33554466, name: "ignoreCase", sons: null}, 
{kind: 1, offset: "multiline", len: 0, typ: NTI33554466, name: "multiline", sons: null}, 
{kind: 1, offset: "source", len: 0, typ: NTI33554450, name: "source", sons: null}, 
{kind: 1, offset: "sticky", len: 0, typ: NTI33554466, name: "sticky", sons: null}, 
{kind: 1, offset: "unicode", len: 0, typ: NTI33554466, name: "unicode", sons: null}, 
{kind: 1, offset: "lastIndex", len: 0, typ: NTI184549387, name: "lastIndex", sons: null}, 
{kind: 1, offset: "input", len: 0, typ: NTI33554450, name: "input", sons: null}, 
{kind: 1, offset: "lastMatch", len: 0, typ: NTI33554450, name: "lastMatch", sons: null}, 
{kind: 1, offset: "lastParen", len: 0, typ: NTI33554450, name: "lastParen", sons: null}, 
{kind: 1, offset: "leftContext", len: 0, typ: NTI33554450, name: "leftContext", sons: null}, 
{kind: 1, offset: "rightContext", len: 0, typ: NTI33554450, name: "rightContext", sons: null}, 
{kind: 1, offset: "hasIndices", len: 0, typ: NTI33554466, name: "hasIndices", sons: null}]};
NTI973078532.node = NNI973078532;
var NNI33555183 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555183.node = NNI33555183;
NTI33555183.base = NTI33555173;
NTI973078532.base = NTI33555183;
NTI973078531.base = NTI973078532;
var NNI654311678 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI973078531, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI973078531, name: "Field1", sons: null}]};
NTI654311678.node = NNI654311678;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555178;
var NNI654311698 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554438, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554438, name: "Field1", sons: null}]};
NTI654311698.node = NNI654311698;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557268, src_33557269, ti_33557270) {
  var result_33557279 = null;

    switch (ti_33557270.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557259(ti_33557270))) {
      result_33557279 = src_33557269;
      }
      else {
        result_33557279 = [src_33557269[0], src_33557269[1]];
      }
      
      break;
    case 19:
            if (dest_33557268 === null || dest_33557268 === undefined) {
        dest_33557268 = {};
      }
      else {
        for (var key in dest_33557268) { delete dest_33557268[key]; }
      }
      for (var key in src_33557269) { dest_33557268[key] = src_33557269[key]; }
      result_33557279 = dest_33557268;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557270.base == null))) {
      result_33557279 = nimCopy(dest_33557268, src_33557269, ti_33557270.base);
      }
      else {
      if ((ti_33557270.kind == 17)) {
      result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {m_type: ti_33557270} : dest_33557268;
      }
      else {
        result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {} : dest_33557268;
      }
      }
      nimCopyAux(result_33557279, src_33557269, ti_33557270.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557269)) { 
        if(dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new src_33557269.constructor(src_33557269);
        } else {
          dest_33557268.set(src_33557269, 0);
        }
        result_33557279 = dest_33557268;
      } else {
        if (src_33557269 === null) {
          result_33557279 = null;
        }
        else {
          if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
            dest_33557268 = new Array(src_33557269.length);
          }
          result_33557279 = dest_33557268;
          for (var i = 0; i < src_33557269.length; ++i) {
            result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557269 === null) {
        result_33557279 = null;
      }
      else {
        if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new Array(src_33557269.length);
        }
        result_33557279 = dest_33557268;
        for (var i = 0; i < src_33557269.length; ++i) {
          result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
        }
      }
    
      break;
    case 28:
            if (src_33557269 !== null) {
        result_33557279 = src_33557269.slice(0);
      }
    
      break;
    default: 
      result_33557279 = src_33557269;
      break;
    }

  return result_33557279;

}

function arrayConstr(len_33557314, value_33557315, typ_33557316) {
        var result = new Array(len_33557314);
    for (var i = 0; i < len_33557314; ++i) result[i] = nimCopy(null, value_33557315, typ_33557316);
    return result;
  

  
}

function mnewString(len_33557003) {
        var result = new Array(len_33557003);
    for (var i = 0; i < len_33557003; i++) {result[i] = 0;}
    return result;
  

  
}

function addInt(a_33557050, b_33557051) {
        var result = a_33557050 + b_33557051;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557324, a_33557325, b_33557326) {
  var result_33557327 = 0;

  BeforeRet: {
    if (((a_33557325 <= i_33557324) && (i_33557324 <= b_33557326))) {
    result_33557327 = i_33557324;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557327;

}

function chckIndx(i_33557319, a_33557320, b_33557321) {
  var result_33557322 = 0;

  BeforeRet: {
    if (((a_33557320 <= i_33557319) && (i_33557319 <= b_33557321))) {
    result_33557322 = i_33557319;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557319, a_33557320, b_33557321);
    }
    
  };

  return result_33557322;

}

function cstrToNimstr(c_33556898) {
      var ln = c_33556898.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556898.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556898.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_33556901) {
  var result_33556902 = null;

    var res_33556943 = newSeq_33556919((s_33556901).length);
    var i_33556944 = 0;
    var j_33556945 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556944 < (s_33556901).length)) break Label2;
          var c_33556946 = s_33556901[i_33556944];
          if ((c_33556946 < 128)) {
          res_33556943[j_33556945] = String.fromCharCode(c_33556946);
          i_33556944 += 1;
          }
          else {
            var helper_33556959 = newSeq_33556919(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556960 = c_33556946.toString(16);
                  if ((((code_33556960) == null ? 0 : (code_33556960).length) == 1)) {
                  helper_33556959.push("%0");;
                  }
                  else {
                  helper_33556959.push("%");;
                  }
                  
                  helper_33556959.push(code_33556960);;
                  i_33556944 += 1;
                  if ((((s_33556901).length <= i_33556944) || (s_33556901[i_33556944] < 128))) {
                  break Label3;
                  }
                  
                  c_33556946 = s_33556901[i_33556944];
                }
            };
++excHandler;
            try {
            res_33556943[j_33556945] = decodeURIComponent(helper_33556959.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556943[j_33556945] = helper_33556959.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556945 += 1;
        }
    };
    if (res_33556943.length < j_33556945) { for (var i = res_33556943.length ; i < j_33556945 ; ++i) res_33556943.push(null); }
               else { res_33556943.length = j_33556945; };
    result_33556902 = res_33556943.join("");

  return result_33556902;

}

function raiseException(e_33556653, ename_33556654) {
    e_33556653.name = ename_33556654;
    if ((excHandler == 0)) {
    unhandledException(e_33556653);
    }
    
    e_33556653.trace = nimCopy(null, rawWriteStackTrace_33556604(), NTI33554449);
    throw e_33556653;

  
}

function subInt(a_33557054, b_33557055) {
        var result = a_33557054 - b_33557055;
    checkOverflowInt(result);
    return result;
  

  
}

function makeNimstrLit(c_33556895) {
      var result = [];
  for (var i = 0; i < c_33556895.length; ++i) {
    result[i] = c_33556895.charCodeAt(i);
  }
  return result;
  

  
}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
var F = {procname: "module parseutils", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strformat", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/strformat.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strformat", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/pure/strformat.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsre", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/js/jsre.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsre", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/js/jsre.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer_33557259(ti_33557260) {
  var result_33557261 = false;

  BeforeRet: {
    result_33557261 = !((ConstSet1[ti_33557260.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557261;

}

function nimCopyAux(dest_33557272, src_33557273, n_33557274) {
    switch (n_33557274.kind) {
    case 0:
      break;
    case 1:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557274.sons.length; i++) {
      nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i]);
    }
    
      break;
    case 3:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
      for (var i = 0; i < n_33557274.sons.length; ++i) {
        nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i][1]);
      }
    
      break;
    }

  
}

function add_33556373(x_33556374, x_33556374_Idx, y_33556375) {
          if (x_33556374[x_33556374_Idx] === null) { x_33556374[x_33556374_Idx] = []; }
      var off = x_33556374[x_33556374_Idx].length;
      x_33556374[x_33556374_Idx].length += y_33556375.length;
      for (var i = 0; i < y_33556375.length; ++i) {
        x_33556374[x_33556374_Idx][off+i] = y_33556375.charCodeAt(i);
      }
    

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_33556812, a_33556813, b_33556814) {
    var Temporary1;

    if ((b_33556814 < a_33556813)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_369098760(i_33556812) || [],[32,110,111,116,32,105,110,32] || [],HEX24_369098760(a_33556813) || [],[32,46,46,32] || [],HEX24_369098760(b_33556814) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function addChars_301990090(result_301990092, result_301990092_Idx, x_301990093, start_301990094, n_301990095) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 43;
    F.filename = "digitsutils.nim";
    var old_301990096 = (result_301990092[result_301990092_Idx]).length;
    F.line = 44;
    if (result_301990092[result_301990092_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_301990095), 0, 2147483647), Temporary1)) { for (var i = result_301990092[result_301990092_Idx].length; i < Temporary1; ++i) result_301990092[result_301990092_Idx].push(0); }
         else {result_301990092[result_301990092_Idx].length = Temporary1; };
    Label2: {
      F.line = 46;
      var iHEX60gensym4_301990110 = 0;
      F.line = 119;
      F.filename = "iterators_1.nim";
      var i_654311826 = 0;
      Label3: {
        F.line = 120;
          Label4: while (true) {
          if (!(i_654311826 < n_301990095)) break Label4;
            F.line = 49;
            F.filename = "digitsutils.nim";
            iHEX60gensym4_301990110 = i_654311826;
            F.line = 49;
            result_301990092[result_301990092_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_301990092[result_301990092_Idx]).length - 1)] = x_301990093.charCodeAt(chckIndx(addInt(start_301990094, iHEX60gensym4_301990110), 0, (x_301990093).length - 1));
            F.line = 122;
            F.filename = "iterators_1.nim";
            i_654311826 = addInt(i_654311826, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars_301990086(result_301990088, result_301990088_Idx, x_301990089) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 55;
    F.filename = "digitsutils.nim";
    addChars_301990090(result_301990088, result_301990088_Idx, x_301990089, 0, ((x_301990089) == null ? 0 : (x_301990089).length));
  framePtr = F.prev;

  
}

function addInt_301990111(result_301990112, result_301990112_Idx, x_301990113) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 111;
    F.filename = "digitsutils.nim";
    addChars_301990086(result_301990112, result_301990112_Idx, ((x_301990113) + ""));
  framePtr = F.prev;

  
}

function addInt_301990129(result_301990130, result_301990130_Idx, x_301990131) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 115;
    F.filename = "digitsutils.nim";
    addInt_301990111(result_301990130, result_301990130_Idx, BigInt(x_301990131));
  framePtr = F.prev;

  
}

function HEX24_369098760(x_369098761) {
  var result_369098762 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 18;
    F.filename = "dollars.nim";
    addInt_301990129(result_369098762, 0, x_369098761);
  framePtr = F.prev;

  return result_369098762[0];

}

function auxWriteStackTrace_33556508(f_33556509) {
  var result_33556510 = [[]];

    var it_33556518 = f_33556509;
    var i_33556519 = 0;
    var total_33556520 = 0;
    var tempFrames_33556521 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555835);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556518 == null)) && (i_33556519 <= 63))) break Label2;
          tempFrames_33556521[i_33556519].Field0 = it_33556518.procname;
          tempFrames_33556521[i_33556519].Field1 = it_33556518.line;
          tempFrames_33556521[i_33556519].Field2 = it_33556518.filename;
          i_33556519 += 1;
          total_33556520 += 1;
          it_33556518 = it_33556518.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556518 == null))) break Label4;
          total_33556520 += 1;
          it_33556518 = it_33556518.prev;
        }
    };
    result_33556510[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556520 == i_33556519))) {
    result_33556510[0].push.apply(result_33556510[0], [40]);;
    result_33556510[0].push.apply(result_33556510[0], HEX24_369098760((total_33556520 - i_33556519)));;
    result_33556510[0].push.apply(result_33556510[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556554 = 0;
      var colontmp__654311818 = 0;
      colontmp__654311818 = (i_33556519 - 1);
      var res_654311820 = colontmp__654311818;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_654311820)) break Label7;
            j_33556554 = res_654311820;
            result_33556510[0].push.apply(result_33556510[0], cstrToNimstr(tempFrames_33556521[j_33556554].Field2));;
            if ((0 < tempFrames_33556521[j_33556554].Field1)) {
            result_33556510[0].push.apply(result_33556510[0], [40]);;
            addInt_301990129(result_33556510, 0, tempFrames_33556521[j_33556554].Field1);
            if (false) {
            result_33556510[0].push.apply(result_33556510[0], [44,32]);;
            addInt_301990129(result_33556510, 0, 0);
            }
            
            result_33556510[0].push.apply(result_33556510[0], [41]);;
            }
            
            result_33556510[0].push.apply(result_33556510[0], [32,97,116,32]);;
            add_33556373(result_33556510, 0, tempFrames_33556521[j_33556554].Field0);
            result_33556510[0].push.apply(result_33556510[0], [10]);;
            res_654311820 -= 1;
          }
      };
    };

  return result_33556510[0];

}

function rawWriteStackTrace_33556604() {
  var result_33556605 = [];

    if (!((framePtr == null))) {
    result_33556605 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10] || []).concat(auxWriteStackTrace_33556508(framePtr) || []), NTI33554449);
    }
    else {
      result_33556605 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556605;

}

function newSeq_33556919(len_33556921) {
  var result_33556922 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 631;
    F.filename = "system.nim";
    result_33556922 = new Array(len_33556921); for (var i = 0 ; i < len_33556921 ; ++i) { result_33556922[i] = null; }  framePtr = F.prev;

  return result_33556922;

}

function unhandledException(e_33556649) {
    var buf_33556650 = [[]];
    if (!(((e_33556649.message).length == 0))) {
    buf_33556650[0].push.apply(buf_33556650[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556650[0].push.apply(buf_33556650[0], e_33556649.message);;
    }
    else {
    buf_33556650[0].push.apply(buf_33556650[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556650[0].push.apply(buf_33556650[0], [32,91]);;
    add_33556373(buf_33556650, 0, e_33556649.name);
    buf_33556650[0].push.apply(buf_33556650[0], [93,10]);;
    buf_33556650[0].push.apply(buf_33556650[0], rawWriteStackTrace_33556604());;
    var cbuf_33556651 = toJSStr(buf_33556650[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556651);
  }
  else {
    throw cbuf_33556651;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33557048) {
        if (a_33557048 > 2147483647 || a_33557048 < -2147483648) raiseOverflow();
  

  
}

function makeStringSlice_654311437(str_654311439) {
  var result_654311440 = ({buf: [null, 0], start: 0, stop: 0});

  var F = {procname: "makeStringSlice.makeStringSlice", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
  framePtr = F;
    F.line = 49;
    F.filename = "strslice.nim";
    F.line = 57;
    var strRef_654311442 = null;
    var strRef_654311442_Idx = 0;
    F.line = 58;
    strRef_654311442 = [[]]; strRef_654311442_Idx = 0;
    F.line = 59;
    strRef_654311442[strRef_654311442_Idx] = nimCopy(null, str_654311439, NTI33554449);
    result_654311440 = nimCopy(result_654311440, {buf: [strRef_654311442, strRef_654311442_Idx], start: 0, stop: subInt((((str_654311439).length) | 0), 1)}, NTI654311427);
  framePtr = F.prev;

  return result_654311440;

}
var F = {procname: "module strslice", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
framePtr = F;
F.line = 63;
F.filename = "strslice.nim";
var EmptyStringSlice_654311480 = makeStringSlice_654311437([]);
F.line = 210;
var PCREFlag_654311733 = new RegExp("\\(\\*\\w+\\)", "g");
F.line = 211;
var comment_654311734 = new RegExp("#[^\\n]*", "g");
F.line = 212;
var whitespace_654311735 = new RegExp("(?: *\\n *)|(?:^ *)|(?: *$)", "g");
F.line = 213;
var slashU_654311736 = new RegExp("\\\\U([0-9a-fA-F]+)", "g");
framePtr = F.prev;
var F = {procname: "module strslice", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function HEX5BHEX5D_654311539(s_654311542, x_654311543) {
  var result_654311544 = [];

  var F = {procname: "[].[]", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/system/indices.nim", line: 0};
  framePtr = F;
    F.line = 83;
    F.filename = "indices.nim";
    var a_654311546 = ((x_654311543.a) | 0);
    F.line = 84;
    var L_654311548 = addInt(subInt(((x_654311543.b) | 0), a_654311546), 1);
    F.line = 85;
    result_654311544 = nimCopy(null, mnewString(chckRange(L_654311548, 0, 2147483647)), NTI33554449);
    Label1: {
      F.line = 86;
      var i_654311553 = 0;
      F.line = 119;
      F.filename = "iterators_1.nim";
      var i_520093878 = 0;
      Label2: {
        F.line = 120;
          Label3: while (true) {
          if (!(i_520093878 < L_654311548)) break Label3;
            F.line = 86;
            F.filename = "indices.nim";
            i_654311553 = i_520093878;
            F.line = 86;
            result_654311544[chckIndx(i_654311553, 0, (result_654311544).length - 1)] = s_654311542[chckIndx(addInt(i_654311553, a_654311546), 0, (s_654311542).length - 1)];
            F.line = 122;
            F.filename = "iterators_1.nim";
            i_520093878 = addInt(i_520093878, 1);
          }
      };
    };
  framePtr = F.prev;

  return result_654311544;

}

function HEX2EHEX2E_654311488(a_654311491, b_654311492) {
  var result_654311495 = ({a: 0, b: 0});

  var F = {procname: ".....", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 416;
    F.filename = "system.nim";
    result_654311495 = nimCopy(result_654311495, {a: a_654311491, b: b_654311492}, NTI654311487);
  framePtr = F.prev;

  return result_654311495;

}

function HEX24_654311485(str_654311486) {
  var result_654311487 = [];

  var F = {procname: "strslice.$", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if ((str_654311486.stop < 0)) {
    F.line = 73;
    F.filename = "strslice.nim";
    result_654311487 = nimCopy(null, [], NTI33554449);
    break BeforeRet;
    }
    
    F.line = 74;
    result_654311487 = nimCopy(null, HEX5BHEX5D_654311539(str_654311486.buf[0][str_654311486.buf[1]], HEX2EHEX2E_654311488(str_654311486.start, str_654311486.stop)), NTI33554449);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_654311487;

}

function replace_654311810(slice_654311811, pattern_654311812, replacement_654311813) {
  var result_654311814 = null;

  var F = {procname: "strslice.replace", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
  framePtr = F;
    F.line = 253;
    F.filename = "strslice.nim";
    result_654311814 = toJSStr(HEX24_654311485(slice_654311811)).replace(pattern_654311812.Field1, toJSStr(replacement_654311813));
  framePtr = F.prev;

  return result_654311814;

}

function toStringSlice_520093724(str_520093726) {
  var result_520093727 = ({buf: [null, 0], start: 0, stop: 0});

  var F = {procname: "toStringSlice.toStringSlice", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
  framePtr = F;
    F.line = 67;
    F.filename = "strslice.nim";
    result_520093727 = nimCopy(result_520093727, makeStringSlice_654311437(str_520093726), NTI654311427);
  framePtr = F.prev;

  return result_520093727;

}

function ure_520093700(pattern_520093702) {
  var result_520093703 = {Field0: null, Field1: null};

  var F = {procname: "ure.ure", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 216;
    F.filename = "strslice.nim";
    var cleanPattern_520093704 = toJSStr(pattern_520093702).replace(PCREFlag_654311733, "").replace(slashU_654311736, "\\u{$1}");
    F.line = 217;
    var colontmp__520093880 = new RegExp(cleanPattern_520093704, "uy");
    F.line = 218;
    var colontmp__520093881 = new RegExp(cleanPattern_520093704, "ug");
    F.line = 217;
    result_520093703 = nimCopy(result_520093703, {Field0: colontmp__520093880, Field1: colontmp__520093881}, NTI654311678);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_520093703;

}

function ure_520093745(pattern_520093747) {
  var result_520093748 = {Field0: null, Field1: null};

  var F = {procname: "ure.ure", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 216;
    F.filename = "strslice.nim";
    var cleanPattern_520093749 = pattern_520093747.replace(PCREFlag_654311733, "").replace(slashU_654311736, "\\u{$1}");
    F.line = 217;
    var colontmp__520093882 = new RegExp(cleanPattern_520093749, "uy");
    F.line = 218;
    var colontmp__520093883 = new RegExp(cleanPattern_520093749, "ug");
    F.line = 217;
    result_520093748 = nimCopy(result_520093748, {Field0: colontmp__520093882, Field1: colontmp__520093883}, NTI654311678);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_520093748;

}

function urex_520093753(pattern_520093755) {
  var result_520093756 = {Field0: null, Field1: null};

  var F = {procname: "urex.urex", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 221;
    F.filename = "strslice.nim";
    var flatPattern_520093757 = pattern_520093755.replace(PCREFlag_654311733, "").replace(comment_654311734, "").replace(whitespace_654311735, "").replace(slashU_654311736, "\\u{$1}");
    F.line = 225;
    var colontmp__520093884 = new RegExp(flatPattern_520093757, "uy");
    F.line = 226;
    var colontmp__520093885 = new RegExp(flatPattern_520093757, "ug");
    F.line = 225;
    result_520093756 = nimCopy(result_520093756, {Field0: colontmp__520093884, Field1: colontmp__520093885}, NTI654311678);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_520093756;

}

function addQuoted_520093836(s_520093838, s_520093838_Idx, x_520093839) {
  var F = {procname: "addQuoted.addQuoted", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 2515;
    F.filename = "system.nim";
    addInt_301990129(s_520093838, s_520093838_Idx, ((x_520093839) | 0));
  framePtr = F.prev;

  
}

function HEX24_520093810(x_520093812) {
  var result_520093813 = [[]];

  var F = {procname: "$.$", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 19;
    F.filename = "miscdollars.nim";
    result_520093813[0] = nimCopy(null, [40], NTI33554449);
    F.line = 21;
    var countHEX60gensym7_520093824 = 0;
    if ((0 < countHEX60gensym7_520093824)) {
    F.line = 23;
    result_520093813[0].push.apply(result_520093813[0], [44,32]);;
    }
    
    F.line = 25;
    result_520093813[0].push.apply(result_520093813[0], [102,105,114,115,116]);;
    F.line = 26;
    result_520093813[0].push.apply(result_520093813[0], [58,32]);;
    F.line = 27;
    countHEX60gensym7_520093824 += 1;
    F.line = 33;
    addQuoted_520093836(result_520093813, 0, x_520093812["Field0"]);
    if ((0 < countHEX60gensym7_520093824)) {
    F.line = 23;
    result_520093813[0].push.apply(result_520093813[0], [44,32]);;
    }
    
    F.line = 25;
    result_520093813[0].push.apply(result_520093813[0], [108,97,115,116]);;
    F.line = 26;
    result_520093813[0].push.apply(result_520093813[0], [58,32]);;
    F.line = 27;
    countHEX60gensym7_520093824 += 1;
    F.line = 33;
    addQuoted_520093836(result_520093813, 0, x_520093812["Field1"]);
    F.line = 39;
    result_520093813[0].push.apply(result_520093813[0], [41]);;
  framePtr = F.prev;

  return result_520093813[0];

}

function sysFatal_268435501(message_268435504) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    F.filename = "fatal.nim";
    raiseException({message: nimCopy(null, message_268435504, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert_268435499(msg_268435500) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 36;
    F.filename = "assertions.nim";
    sysFatal_268435501(msg_268435500);
  framePtr = F.prev;

  
}

function failedAssertImpl_268435541(msg_268435542) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/Users/di68kap/.choosenim/toolchains/nim-2.0.2/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    F.filename = "assertions.nim";
    raiseAssert_268435499(msg_268435542);
  framePtr = F.prev;

  
}

function str_654311554(str_654311555) {
  var result_654311556 = null;
  var result_654311556_Idx = 0;

  var F = {procname: "strslice.str", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
  framePtr = F;
    F.line = 76;
    F.filename = "strslice.nim";
    result_654311556 = str_654311555.buf[0]; result_654311556_Idx = str_654311555.buf[1];
  framePtr = F.prev;

  return [result_654311556, result_654311556_Idx];

}

function find_654311750(slice_654311751, pattern_654311752, start_654311753, size_654311754) {
    var Temporary1;

  var result_654311757 = {Field0: 0, Field1: 0};

  var F = {procname: "strslice.find", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if (!(((0 <= start_654311753) && (start_654311753 <= addInt(subInt(slice_654311751.stop, slice_654311751.start), 1))))) {
    F.line = 232;
    F.filename = "strslice.nim";
    failedAssertImpl_268435541(makeNimstrLit("/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim(232, 5) `start >= 0 and start <= slice.stop - slice.start + 1` "));
    }
    
    F.line = 233;
    pattern_654311752.Field1.lastIndex = addInt(start_654311753, slice_654311751.start);
    F.line = 234;
    var s_654311763 = toJSStr((Temporary1 = str_654311554(slice_654311751), Temporary1)[0][Temporary1[1]]);
    F.line = 235;
    var m_654311764 = (pattern_654311752.Field1.exec(s_654311763) || []);
    if ((0 < (m_654311764).length)) {
    F.line = 237;
    var l_654311769 = (((cstrToNimstr(m_654311764[chckIndx(0, 0, (m_654311764).length - 1)])).length) | 0);
    F.line = 238;
    var a_654311770 = subInt(subInt(pattern_654311752.Field1.lastIndex, slice_654311751.start), ((((m_654311764[chckIndx(0, 0, (m_654311764).length - 1)]) == null ? 0 : (m_654311764[chckIndx(0, 0, (m_654311764).length - 1)]).length)) | 0));
    if (((size_654311754 < 0) || (a_654311770 <= addInt(start_654311753, size_654311754)))) {
    F.line = 240;
    var colontmp__520093886 = a_654311770;
    F.line = 240;
    var colontmp__520093887 = subInt(addInt(a_654311770, l_654311769), 1);
    F.line = 240;
    result_654311757 = nimCopy(result_654311757, {Field0: colontmp__520093886, Field1: colontmp__520093887}, NTI654311698);
    break BeforeRet;
    }
    
    }
    
    F.line = 241;
    var colontmp__520093888 = (-1);
    F.line = 241;
    var colontmp__520093889 = (-2);
    F.line = 241;
    result_654311757 = nimCopy(result_654311757, {Field0: colontmp__520093888, Field1: colontmp__520093889}, NTI654311698);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_654311757;

}

function matchLen_654311788(slice_654311789, pattern_654311790, location_654311791) {
    var Temporary1;

  var result_654311792 = 0;

  var F = {procname: "strslice.matchLen", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if (!(((0 <= location_654311791) && (location_654311791 <= addInt(subInt(slice_654311789.stop, slice_654311789.start), 1))))) {
    F.line = 244;
    F.filename = "strslice.nim";
    failedAssertImpl_268435541(makeNimstrLit("/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim(244, 5) `location >= 0 and location <= slice.stop - slice.start + 1` "));
    }
    
    F.line = 245;
    pattern_654311790.Field0.lastIndex = addInt(location_654311791, slice_654311789.start);
    F.line = 246;
    var m_654311798 = (toJSStr((Temporary1 = str_654311554(slice_654311789), Temporary1)[0][Temporary1[1]]).match(pattern_654311790.Field0) || []);
    if ((0 < (m_654311798).length)) {
    if (!(((m_654311798).length == 1))) {
    F.line = 248;
    failedAssertImpl_268435541(makeNimstrLit("/Users/di68kap/Entwicklung/DHParser/nim_rewrite/src/nimparser/strslice.nim(248, 7) `m.len == 1` "));
    }
    
    F.line = 249;
    result_654311792 = (((cstrToNimstr(m_654311798[chckIndx(0, 0, (m_654311798).length - 1)])).length) | 0);
    break BeforeRet;
    }
    
    F.line = 250;
    result_654311792 = (-1);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_654311792;

}
var F = {procname: "module unicode_regex", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/scratch/unicode_regex.nim", line: 0};
framePtr = F;
F.line = 3;
F.filename = "unicode_regex.nim";
var rs_520093698 = makeNimstrLit("_|:|[A-Z]|[a-z]\x0A             |[\\u00C0-\\u00D6]|[\\u00D8-\\u00F6]|[\\u00F8-\\u02FF]\x0A             |[\\u0370-\\u037D]|[\\u037F-\\u1FFF]|[\\u200C-\\u200D]\x0A             |[\\u2070-\\u218F]|[\\u2C00-\\u2FEF]|[\\u3001-\\uD7FF]\x0A             |[\\uF900-\\uFDCF]|[\\uFDF0-\\uFFFD]\x0A             |[\\U00010000-\\U000EFFFF]");
F.line = 25;
var prs_520093732 = replace_654311810(toStringSlice_520093724(rs_520093698), ure_520093700([92,92,85,40,91,48,45,57,97,45,102,65,45,70,93,43,41]), [92,117,123,36,49,125]);
F.line = 26;
var r_520093736 = ure_520093700(makeNimstrLit("_|:|[A-Z]|[a-z]|\\x09\x0A             |[\\u00C0-\\u00D6]|[\\u00D8-\\u00F6]|[\\u00F8-\\u02FF]\x0A             |[\\u0370-\\u037D]|[\\u037F-\\u1FFF]|[\\u200C-\\u200D]\x0A             |[\\u2070-\\u218F]|[\\u2C00-\\u2FEF]|[\\u3001-\\uD7FF]\x0A             |[\\uF900-\\uFDCF]|[\\uFDF0-\\uFFFD]\x0A             |[\\u{00010000}-\\u{000EFFFF}]"));
F.line = 32;
var rs2_520093737 = makeNimstrLit("(?:(?!-)(?:\\x09|\\x0A|\\x0D|[\\u0020-\\uD7FF]|[\\uE000-\\uFFFD]|[\\U00010000-\\U0010FFFF]))+");
F.line = 33;
var prs2_520093744 = replace_654311810(toStringSlice_520093724(rs2_520093737), ure_520093700([92,92,85,40,91,48,45,57,97,45,102,65,45,70,93,43,41]), [92,117,123,36,49,125]);
F.line = 34;
rawEcho(cstrToNimstr(prs2_520093744));
F.line = 35;
var rr_520093752 = ure_520093745(prs2_520093744);
F.line = 38;
rawEcho(cstrToNimstr(prs_520093732));
F.line = 39;
var rx_520093760 = urex_520093753(prs_520093732);
F.line = 40;
rawEcho(HEX24_520093810(find_654311750(toStringSlice_520093724([194,160]), ure_520093700([40,63,58,40,63,33,92,93,92,93,62,41,91,94,60,38,93,41,43]), 0, (-1))));
F.line = 41;
rawEcho(HEX24_369098760(((matchLen_654311788(toStringSlice_520093724([194,160]), ure_520093700([40,63,58,40,63,33,92,93,92,93,62,41,91,94,60,38,93,41,43]), 0)) | 0)));
F.line = 42;
rawEcho([50]);
F.line = 44;
rawEcho(HEX24_520093810(find_654311750(toStringSlice_520093724([195,164]), ure_520093700([40,63,58,40,63,33,92,93,92,93,62,41,91,94,60,38,93,41,43]), 0, (-1))));
F.line = 45;
rawEcho(HEX24_369098760(((matchLen_654311788(toStringSlice_520093724([195,164]), ure_520093700([40,63,58,40,63,33,92,93,92,93,62,41,91,94,60,38,93,41,43]), 0)) | 0)));
F.line = 46;
rawEcho([50]);
framePtr = F.prev;
var F = {procname: "module unicode_regex", prev: framePtr, filename: "/Users/di68kap/Entwicklung/DHParser/nim_rewrite/scratch/unicode_regex.nim", line: 0};
framePtr = F;
framePtr = F.prev;
