expression = term  { ("+" | "-") term}
term       = factor  { ("*"|"/") factor}
factor     = constant | variable | "("  expression  ")"
variable   = "x" | "y" | "z"
constant   = digit {digit}
digit      = "0" | "1" | "..." | "9"
test       = digit constant variable


