# EBNF-Syntax für MLW-Artikel

@ comment       =  /#.*(?:\n|$)/    # Kommentare beginnen mit '#' und reichen bis zum Zeilenende
@ whitespace    =  /\s*/            # Auch Zeilenspränge zählen als Leerraum
@ literalws     =  both             # Leerraum vor und nach Literalen wird automatisch entfernt


Artikel         = [LEER]
                  §LemmaPosition  [ArtikelKopf]  §BedeutungsPosition
                  [LEER]  DATEI_ENDE


#### LEMMA-POSITION ##########################################################

LemmaPosition   = "LEMMA"  §Lemma  [LemmaVarianten]  §GrammatikPosition

Lemma           = [_tll]  /[a-z]+/~
_tll            = "*"



LemmaVarianten  = "(" §LVariante  { "," §LVariante }  [LVZusatz] §")"

LVariante       = ~/(?:[a-z]|-)+/~  # Buchstabenfolge mit Trennzeichen "-"
LVZusatz        = _typ
_typ            = "sim."            # | "sim..."



#### GRAMMATIK-POSITION ######################################################

GrammatikPosition = "GRAMMATIK"  §_wortart §";"  §Flexionen  [_genus]  [GrammatikVarianten] ["."]

_wortart        = "nomen"  | "n." |
                  "verb"   | "v." |
                  "adverb" | "adv." |
                  "adjektiv" | "adj."


GrammatikVarianten = "("  §GVariante  { ";" §GVariante }  §")"
GVariante       = Flexionen  [_genus]  ":"  Beleg

Flexionen       = Flexion { "," Flexion }
Flexion         = ~/-[a-z]+/~

_genus          = "maskulinum" | "m." |
                  "femininum" | "f." |
                  "neutrum" | "n."



#### ARTIKEL-KOPF ############################################################

ArtikelKopf     = SchreibweisenPosition
SchreibweisenPosition =  { "SCHREIBWEISE" §SWTyp ":" { "  " §SWVariante }+ }+
SWTyp           = "script."
SWVariante      = Schreibweise ":" Beleg



#### BEDEUTUNGS-POSITION #####################################################




Beleg           = Verweis
Verweis         = ~/>\w+/~

VerweisZiel     = ~/<\w+/>/~



#### MISZELLANEEN ############################################################

LEER            = ~//
DATEI_ENDE      = !/./
NIEMALS         = /(?!.)/