# hey, you

doc = re | char | char_range | multiple1 | multiple2 | multiple3 | mutliple4
re = /abc*/
char = #x32  # shell-style comment
char_range = [#xDFF88-#xEEFF00]   /*
        C-style comment
*/  multiple1 = `a` * 3
multiple2 = 4 * `b`
multiple3 = `c`{3}
multiple4 = `d`{2,5}
