# A variant of an Arithmetic-grammar

# @drop = whitespace, strings

formulae = ~ expression { expression }

expression = addition | subtraction | term
  addition    = expression "+"~ term
  subtraction = expression "-"~ term

term       = multiplication | division | factor
  multiplication = term "*"~ factor
  division       = term ":"~ factor

factor = group | number
  group  = "("~ expression ")"~
  number = /0/~ | /[1-9]/ { /[0-9]/ } ~


