# @drop = whitespace

formulae   = ~ expression { ~ expression } ~
expression = term  { ("+" | "-" | "*" | ":") term }
term       = number | group
group      = "(" expression ")"

number     = /0/ | /[1-9]/ { /[0-9]/ }

